name: Mypy

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        name: Mypy
        steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.8
          uses: actions/setup-python@v1
          with:
              python-version: 3.8
        - name: Install Mypy
          run: pip install mypy types-requests
        - name: Mypy
          run: mypy .
