name: Unit tests

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        name: Unit tests
        steps:
        - uses: actions/checkout@v1
        - name: Set up Python 3.8
          uses: actions/setup-python@v1
          with:
              python-version: 3.8
        - name: Install
          run: |
              pip install 'git+https://github.com/KSP-CKAN/NetKAN-Infra#subdirectory=netkan'
              pip install .
        - name: Unit tests
          run: python -m unittest -v
